# Generated by Django 5.0 on 2023-12-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('capacity', models.IntegerField(default=20, verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('size', models.IntegerField(default=1, verbose_name='size')),
                ('price', models.IntegerField(verbose_name='price')),
                ('stores', models.ManyToManyField(related_name='products', to='stores.store')),
            ],
        ),
    ]
