# Generated by Django 5.0 on 2023-12-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_product_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.AddField(
            model_name='store',
            name='stores',
            field=models.ManyToManyField(blank=True, default=None, related_name='stores', to='stores.product'),
        ),
    ]
