# Generated by Django 5.0 on 2023-12-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_product_stores_store_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='stores',
            new_name='products',
        ),
    ]
